# Generated by Django 4.2.13 on 2024-07-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0002_accountemail_category_resetpassword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='cv',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
