# Generated by Django 4.2.13 on 2024-07-31 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0004_remove_employer_cv_category_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='jobs',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('farming', 'Farming'), ('livestock', 'Livestock'), ('agro_tourism', 'Agro Tourism')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.category'),
        ),
    ]
