# Generated by Django 4.2.13 on 2024-07-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0005_remove_category_jobs_category_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='image',
            field=models.ImageField(blank=True, upload_to='jobs_images/'),
        ),
    ]
